# Generated by Django 4.0.3 on 2023-07-25 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='phone_numer',
            new_name='phone_number',
        ),
    ]
