# Generated by Django 4.0.3 on 2023-07-25 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0002_rename_phone_numer_customer_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automobilevo',
            name='import_href',
        ),
    ]
